[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = "0.5.1"
uuid = { version = "1.8.0", features = ["v4", "fast-rng"] }
serde = { version = "*", features = ["derive"] }
serde_json = "1.0.117"
serde_millis = "0.1.1"
